apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-manifest
  namespace: web
spec:
  params:
    - name: repo-url
      type: string
    - name: image
      type: string
  workspaces:
    - name: source
  steps:
    - name: git-commit-new-tag
      image: alpine/git
      env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: username
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: password
      script: |
        #!/bin/sh
        set -e
        git config --global --add safe.directory $(workspaces.source.path)
        cd $(workspaces.source.path)
        git config user.email "tekton-bot@example.com"
        git config user.name "tekton-bot"
        sed -i "s#image: .*#image: $(params.image)#" k8s/deployment.yaml
        git add k8s/deployment.yaml
        git commit -m "ci: update image to $(params.image)" || echo "nothing to commit"
        AUTH_URL=$(echo "$(params.repo-url)" | sed "s#https://#https://${GIT_USERNAME}:${GIT_PASSWORD}@#")
        git push "$AUTH_URL" HEAD:main