apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
  namespace: web
spec:
  params:
    - name: image
      type: string
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      args:
        - --dockerfile=app/Dockerfile
        - --context=/workspace/source/app
        - --destination=$(params.image)
      computeResources:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "768Mi"
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: ghcr-credentials
        items:
          - key: .dockerconfigjson
            path: config.json